// Pixel formats (retro_pixel_format)
export const RETRO_PIXEL_FORMAT_0RGB1555 = 0;
export const RETRO_PIXEL_FORMAT_XRGB8888 = 1;
export const RETRO_PIXEL_FORMAT_RGB565 = 2;

// Input device types
export const RETRO_DEVICE_NONE = 0;
export const RETRO_DEVICE_JOYPAD = 1;
export const RETRO_DEVICE_MOUSE = 2;
export const RETRO_DEVICE_KEYBOARD = 3;
export const RETRO_DEVICE_LIGHTGUN = 4;
export const RETRO_DEVICE_ANALOG = 5;
export const RETRO_DEVICE_POINTER = 6;

// Joypad button IDs (RETRO_DEVICE_ID_JOYPAD_*)
export const JOYPAD_B = 0;
export const JOYPAD_Y = 1;
export const JOYPAD_SELECT = 2;
export const JOYPAD_START = 3;
export const JOYPAD_UP = 4;
export const JOYPAD_DOWN = 5;
export const JOYPAD_LEFT = 6;
export const JOYPAD_RIGHT = 7;
export const JOYPAD_A = 8;
export const JOYPAD_X = 9;
export const JOYPAD_L = 10;
export const JOYPAD_R = 11;
export const JOYPAD_L2 = 12;
export const JOYPAD_R2 = 13;
export const JOYPAD_L3 = 14;
export const JOYPAD_R3 = 15;
export const JOYPAD_MASK = 256; // Special ID for bitmask query

// Analog index
export const RETRO_DEVICE_INDEX_ANALOG_LEFT = 0;
export const RETRO_DEVICE_INDEX_ANALOG_RIGHT = 1;
export const RETRO_DEVICE_INDEX_ANALOG_BUTTON = 2;
export const RETRO_DEVICE_ID_ANALOG_X = 0;
export const RETRO_DEVICE_ID_ANALOG_Y = 1;

// Memory types
export const RETRO_MEMORY_SAVE_RAM = 0;
export const RETRO_MEMORY_RTC = 1;
export const RETRO_MEMORY_SYSTEM_RAM = 2;
export const RETRO_MEMORY_VIDEO_RAM = 3;

// Region
export const RETRO_REGION_NTSC = 0;
export const RETRO_REGION_PAL = 1;

// Environment callback commands
export const RETRO_ENVIRONMENT_SET_ROTATION = 1;
export const RETRO_ENVIRONMENT_GET_OVERSCAN = 2;
export const RETRO_ENVIRONMENT_GET_CAN_DUPE = 3;
export const RETRO_ENVIRONMENT_SET_MESSAGE = 6;
export const RETRO_ENVIRONMENT_SET_MESSAGE_EXT = 60;
export const RETRO_ENVIRONMENT_SHUTDOWN = 7;
export const RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL = 8;
export const RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY = 9;
export const RETRO_ENVIRONMENT_SET_PIXEL_FORMAT = 10;
export const RETRO_ENVIRONMENT_SET_INPUT_DESCRIPTORS = 11;
export const RETRO_ENVIRONMENT_SET_KEYBOARD_CALLBACK = 12;
export const RETRO_ENVIRONMENT_GET_VARIABLE = 15;
export const RETRO_ENVIRONMENT_SET_VARIABLES = 16;
export const RETRO_ENVIRONMENT_GET_VARIABLE_UPDATE = 17;
export const RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME = 18;
export const RETRO_ENVIRONMENT_GET_LIBRETRO_PATH = 19;
export const RETRO_ENVIRONMENT_SET_FRAME_TIME_CALLBACK = 21;
export const RETRO_ENVIRONMENT_SET_AUDIO_CALLBACK = 22;
export const RETRO_ENVIRONMENT_GET_RUMBLE_INTERFACE = 23;
export const RETRO_ENVIRONMENT_GET_INPUT_DEVICE_CAPABILITIES = 24;
export const RETRO_ENVIRONMENT_GET_LOG_INTERFACE = 27;
export const RETRO_ENVIRONMENT_GET_PERF_INTERFACE = 28;
export const RETRO_ENVIRONMENT_GET_CORE_ASSETS_DIRECTORY = 30;
export const RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY = 31;
export const RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO = 32;
export const RETRO_ENVIRONMENT_SET_SUBSYSTEM_INFO = 34;
export const RETRO_ENVIRONMENT_SET_CONTROLLER_INFO = 35;
export const RETRO_ENVIRONMENT_SET_MEMORY_MAPS = 36;
export const RETRO_ENVIRONMENT_SET_GEOMETRY = 37;
export const RETRO_ENVIRONMENT_GET_USERNAME = 38;
export const RETRO_ENVIRONMENT_GET_LANGUAGE = 39;
export const RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS = 42;
export const RETRO_ENVIRONMENT_GET_VFS_INTERFACE = 45;
export const RETRO_ENVIRONMENT_GET_AUDIO_VIDEO_ENABLE = 47;
export const RETRO_ENVIRONMENT_GET_INPUT_BITMASKS = 52;
export const RETRO_ENVIRONMENT_SET_SERIALIZATION_QUIRKS = 62;
export const RETRO_ENVIRONMENT_SET_CORE_OPTIONS_UPDATE_DISPLAY_CALLBACK = 63;
export const RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION = 53;
export const RETRO_ENVIRONMENT_SET_CORE_OPTIONS = 53;
export const RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2 = 67;

// Log levels
export const RETRO_LOG_DEBUG = 0;
export const RETRO_LOG_INFO = 1;
export const RETRO_LOG_WARN = 2;
export const RETRO_LOG_ERROR = 3;
